config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  resources :welcome, only: [:index]


  resources :products do
    get 'search', on: :collection
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, uniqueness: { scope: :country }, :presence => true
  validates :country, :cost, :presence => true
  before_save(:normalize_text)

  has_many :reviews

  scope :last_three, -> {order(:created_at).limit(3)}

  scope :most_reviews, -> {(
    select("products.name, products.id, count(reviews.id) as product_reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("product_reviews_count DESC")
    .limit(1)
    )}

  scope :search, -> (country_param) { where("country like ?", "%#{country_param}%")}

private
  def normalize_text
    self.name = name.downcase.titleize
    self.country = country.downcase.capitalize
  end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :author, :presence => true
  validates :content, :presence => true, :length => { :minimum => 50, :maximum => 250}
  validates :rating, :presence => true, numericality: { :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5}


  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def search
    country = params[:q].capitalize
    @products = Product.search(country)
    render :index
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "You successfully created a new product!"
      redirect_to products_path
    else
      flash[:alert] = "Please try again"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Edit Successful"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Please Try Again"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product was successfully deleted"
    redirect_to products_path
  end


private
  def product_params
    params.require(:product).permit(:name, :country, :cost)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review Added Successfully"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @products = Product.last_three
    @most_reviewed_product = Product.most_reviews
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosSpecialityFoods</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <nav class="navbar  navbar-inverse bg-primary">
      <nav class="navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag "mario.png", class: "thumbnail2" %>
        <% end %>
      </nav>
      <nav>
        <p class="navbar-brand"><%= link_to "Products", products_path %></p>
      </nav>
    </nav>

    <div class="container">
      
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<div class="container">

  <%= form_for @product do |f| %>
  <%= f.label :name, "Product Name" %>
  <%= f.text_field :name %>
  <%= f.label :country, "Country of Origin" %>
  <%= f.text_field :country %>
  <%= f.label :cost, "Product Cost" %>
  <%= f.text_field :cost %>
  <%= f.submit %>
  <% end %>

</div>

app/views/products/edit.html.erb
<h1> Edit Product </h1>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">

  <h1> These Are All The Products At Super Mario's Speciality Food Shop! </h1>



  <div class="row">
    <div class="col-md-6">
      <table>
        <tr>
          <th>Product Name</th>
          <th>Cost</th>
          <th>Country of Origin</th>
        </tr>
        <% @products.each do |product| %>
        <tr>
          <td> <%= link_to product.name, product_path(product) %> </td>
          <td>$ <%= product.cost %> </td>
          <td> <%= product.country %> </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-6">
      <div class="button">
        <%= link_to "Enter A New Product", new_product_path %>
      </div>
      <br>
      <%= form_tag("products/search", method: "get") do %>
        <%= label_tag(:q, "Search By Country:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>


</div>

app/views/products/new.html.erb
<h1> Enter A New Product </h1>

<%= render 'form' %>

app/views/products/show.html.erb
<br>
<%= link_to "Return To Product List", products_path %>

  <h1> <%= @product.name %> </h1>
  <h3>Country of Origin: <%= @product.country %> </h3>
  <h4>$ <%= @product.cost %> </h4>

  <% if @product.reviews.any? %>
    <% @product.reviews.each do |review| %>
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            Author: <%= review.author %> Rating: <%= review.rating %>
          </div>
          <div class="panel-body">
            <%= review.content %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <h3> Average Rating: <%= @product.reviews.average(:rating).round(2) %> </h3>
  <% end %>

<br>
  <div class="button">
    <%= link_to "Add Review", new_product_review_path(@product) %>
  </div>
<br>


<br>

<%= link_to "Edit", edit_product_path(@product) %>
<br>
<%= link_to "Delete", product_path(@product), data: {
  confirm: "Are you sure?",
  method: "delete"} %>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author, "Author" %>
  <%= f.text_field :author %>
  <br>
  <br>
  <%= f.label :content, "Review" %>
  <%= f.text_area :content, cols: 40, rows: 5 %>
  <br>
  <br>
  <%= f.label :rating, "Rating (1-5)" %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1> Create New Review </h1>


<%= render 'form' %>

app/views/welcome/index.html.erb
<h1 class="header"> Super Mario's Speciality Foods </h1>

<div class="bg"></div>



<div class="row">
  <div class="col-md-4">
    <div class="home-panel panel panel-default">
      <div class="panel-heading">
        <h1>3 Most Recent Products</h1>
      </div>
      <div class="panel-body">
        <ul>
          <% @products.each do |product| %>
          <li> <%= link_to product.name, product_path(product) %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
      <div class="home-panel panel panel-default">
        <div class="panel-heading">
          <h1>Product With Most reviews</h1>
        </div>
        <div class="panel-body">
          <% @most_reviewed_product.each do |product| %>
          <h3> <%= link_to product.name, product_path(product) %> </h3>
          <% end %>
        </div>
      </div>
  </div>

</div>